/**
 * Requests per IP and minute for each route of the public API, on top of the general limit
 * (api/http.ts). Every route has its own: limits.test.ts reads the route modules and checks it.
 */
export const API_LIMITS: Readonly<Record<string, number>> = Object.freeze({
  '/api/link/describe': 30,
  '/api/link/confirm': 10,
  '/api/handoff/describe': 30,
  '/api/handoff/result': 20,
  '/api/recovery/challenge': 20,
  '/api/recovery/wallets': 10,
  '/api/recovery/export': 5,
  '/api/recovery/export/status': 60,
  '/api/recovery/export/collect': 10,
  '/api/recovery/export/cancel': 10,
  '/api/recovery/destination': 10,
  '/api/telegram/request': 30,
  '/api/telegram/approve': 10,
  '/api/web/login': 10,
  '/api/web/logout': 20,
  '/api/web/wallets': 60,
  '/api/web/wallets/create': 10,
  '/api/web/wallets/rename': 20,
  '/api/web/wallets/delete': 10,
  '/api/web/wallets/order': 20,
  '/api/web/trade/quote': 20,
  '/api/web/trade/execute': 20,
  '/api/web/trade/cancel': 30,
  '/api/web/trade/status': 120,
  '/api/web/send/review': 20,
  '/api/web/send/execute': 10,
  '/api/web/send/status': 120,
  '/api/web/unwrap/review': 20,
  '/api/web/unwrap/execute': 10,
  '/api/web/unwrap/status': 120,
  '/api/web/bots': 60,
  '/api/web/bots/save': 20,
  '/api/web/bots/detail': 120,
  '/api/web/bots/start': 10,
  '/api/web/bots/pause': 20,
  '/api/web/bots/resume': 20,
  '/api/web/bots/stop': 20,
  '/api/web/bots/delete': 10,
  '/api/kits/burns': 60,
  // Bridge & Buy: a quote asks NEAR Intents (and prices $KITS), a start makes a deposit address.
  '/api/bridge/assets': 60,
  '/api/bridge/quote': 30,
  '/api/bridge/start': 10,
  '/api/bridge/deposit': 20,
  '/api/bridge/order': 120,
  '/api/bridge/orders': 60,
  '/api/bridge/settle': 20,
  '/api/bridge/solana': 60,
})
